/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//************ CLASES IMPORTADAS *************
import Model.CardClass;
import Model.OrderClass;
import Model.CompoundClass;
import Model.OrderStage;
import Model.SimpleorderClass;
import Model.StocktakingClass;
import java.util.LinkedList;
import javafx.stage.Stage;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import sun.util.calendar.CalendarUtils;

/**
 *
 * @author LORENA FAJARDO
 */
public class UI_Order extends javax.swing.JFrame {

    //************ LISTAS *****************
    LinkedList<StocktakingClass> stocktaking_list = new LinkedList<>();
    LinkedList<OrderClass> order_list = new LinkedList<>();
    LinkedList<SimpleorderClass> simple_list = new LinkedList<>();
    LinkedList<CardClass> card_list = new LinkedList<>();
    LinkedList<Integer> value_pay_list = new LinkedList();
    LinkedList<CompoundClass> compound_list = new LinkedList<>();
    LinkedList<OrderStage> orderstage_list = new LinkedList<>();
    LinkedList<OrderStage> charge_list = new LinkedList<>();
    LinkedList<OrderStage> distribution_list = new LinkedList<>();
    LinkedList<OrderStage> confirmation_list = new LinkedList<>();

    /**
     * Creates new form UI_Order
     */
    public UI_Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_price_stocktaking = new javax.swing.JTextField();
        txt_quantity_stocktaking = new javax.swing.JTextField();
        btn_add_stock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stock_list = new javax.swing.JList<>();
        txt_name_product_stocktaking = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_name_client_order = new javax.swing.JTextField();
        txt_address_client = new javax.swing.JTextField();
        txt_phone_client = new javax.swing.JTextField();
        txt_email_client = new javax.swing.JTextField();
        txt_quantity_order = new javax.swing.JTextField();
        btn_add_order = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        order_client_list = new javax.swing.JList<>();
        txt_product_order = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txt_name_c_pay = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_card_pay = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_add_card = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_card_number = new javax.swing.JTextField();
        btn_amount_card_pay = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarea_amount_card = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_recharge_card = new javax.swing.JTextField();
        btn_recharge_card = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btn_order_pay = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        order_pay_list = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area_total_pay = new javax.swing.JTextArea();
        btn_pay_now = new javax.swing.JButton();
        btn_pay_after = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        order_stage_list = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        txt_name_client_stage1 = new javax.swing.JTextField();
        btn_order_stage = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        distribution_stage_list = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        txt_name_client_stage2 = new javax.swing.JTextField();
        btn_distribution_stage = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        confirmation_stage_list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Esta información es solicitada unicamente a funcionarios de la empresa, si usted es cliente por favor haga caso omiso a esta pestaña.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("INFORMACIÓN DE INVENTARIO");

        jLabel3.setText("Referencia del producto");

        jLabel4.setText("Precio del producto");

        jLabel5.setText("Cantidad del producto disponible ");

        btn_add_stock.setText("Añadir al inventario");
        btn_add_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_stockActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(stock_list);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_price_stocktaking)
                            .addComponent(txt_quantity_stocktaking)
                            .addComponent(txt_name_product_stocktaking, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(btn_add_stock))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_name_product_stocktaking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_price_stocktaking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_quantity_stocktaking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_add_stock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("INVENTARIO EMPRESA", jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CLIENTE");

        jLabel7.setText("Nombre completo");

        jLabel8.setText("Dirección");

        jLabel9.setText("Telefono celular");

        jLabel10.setText("Correo electronico");

        jLabel11.setText("Seleccione el producto que quiere comprar");

        jLabel12.setText("Cantidad del producto a comprar");

        btn_add_order.setText("Enviar orden");
        btn_add_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_orderActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(order_client_list);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name_client_order)
                            .addComponent(txt_address_client)
                            .addComponent(txt_phone_client)
                            .addComponent(txt_email_client)
                            .addComponent(txt_quantity_order)
                            .addComponent(txt_product_order, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btn_add_order))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_name_client_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_address_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_phone_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_email_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_product_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_quantity_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_add_order)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("REGISTRO DE ORDEN", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("INFORMACIÓN CUENTA BANCARIA");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("Nombre Completo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Numero de tarjeta de credito");

        jLabel18.setText("Agregue la cuenta bancaria con la cual realizará el pago de la orden");

        btn_add_card.setText("Agregar");
        btn_add_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_cardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_name_c_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_card_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add_card))))
                .addGap(24, 24, 24))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name_c_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_card_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add_card)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2609, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel17.setText("CONSULTAR SALDO ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Numero de la tarjeta");

        btn_amount_card_pay.setText("Consultar saldo");
        btn_amount_card_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_amount_card_payActionPerformed(evt);
            }
        });

        txtarea_amount_card.setColumns(20);
        txtarea_amount_card.setRows(5);
        jScrollPane3.setViewportView(txtarea_amount_card);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txt_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btn_amount_card_pay))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_amount_card_pay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setText("RECARGAR CUENTA");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("¿Cuanto dinero quiere recargar en su cuenta? ");

        txt_recharge_card.setForeground(new java.awt.Color(102, 102, 102));
        txt_recharge_card.setText("0");

        btn_recharge_card.setText("Recargar cuenta");
        btn_recharge_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recharge_cardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(txt_recharge_card, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(btn_recharge_card)
                        .addGap(131, 131, 131))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_recharge_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_recharge_card)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("REALIZAR PAGO");

        btn_order_pay.setText("Consultar orden");
        btn_order_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order_payActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(order_pay_list);

        txt_area_total_pay.setColumns(20);
        txt_area_total_pay.setRows(5);
        jScrollPane5.setViewportView(txt_area_total_pay);

        btn_pay_now.setText("Pagar ahora");
        btn_pay_now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pay_nowActionPerformed(evt);
            }
        });

        btn_pay_after.setText("Pagar despues");
        btn_pay_after.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pay_afterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_order_pay)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_pay_now, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btn_pay_after, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order_pay)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pay_now)
                    .addComponent(btn_pay_after))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2422, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("PROCESO DE PAGO", jPanel1);

        jPanel7.setBackground(new java.awt.Color(102, 255, 204));

        jLabel19.setText("ORDENES POR COBRAR");

        jScrollPane4.setViewportView(order_stage_list);

        jLabel25.setText("Si ya se realizo el pago, por favor escriba el nombre del cliente y click en aceptar ");

        btn_order_stage.setText("Aceptar");
        btn_order_stage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order_stageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txt_name_client_stage1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_order_stage)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_order_stage)
                    .addComponent(txt_name_client_stage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel20.setText("ORDENES EN DISTRIBUCIÓN");

        jScrollPane7.setViewportView(distribution_stage_list);

        jLabel26.setText("Si ya se realizo el envio, por favor escriba el nombre del cliente y click en aceptar ");

        btn_distribution_stage.setText("Aceptar");
        btn_distribution_stage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distribution_stageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txt_name_client_stage2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_distribution_stage)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_distribution_stage)
                    .addComponent(txt_name_client_stage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(24, 24, 24))
        );

        jLabel21.setText(" ORDENES CONFIRMADAS");

        jScrollPane8.setViewportView(confirmation_stage_list);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("ESTADO DE LA ORDEN", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//********************RECIBIR LA INFORMACIÓN DE ENTRADA***************************************
    private void btn_add_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_stockActionPerformed

        String name_p = txt_name_product_stocktaking.getText();
        int price_p = Integer.parseInt(txt_price_stocktaking.getText());
        int quantity_p = Integer.parseInt(txt_quantity_stocktaking.getText());

        StocktakingClass stocktaking = new StocktakingClass(name_p, price_p, quantity_p);
        stocktaking_list.add(stocktaking);
        add_stock_list();
        clean_fields();
    }//GEN-LAST:event_btn_add_stockActionPerformed

    private void btn_add_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_orderActionPerformed
        String name_c = txt_name_client_order.getText();
        String address_c = txt_address_client.getText();
        String phone_c = txt_phone_client.getText();
        String email_c = txt_email_client.getText();

        String product_order = txt_product_order.getText();
        int quantity_products_order = Integer.parseInt(txt_quantity_order.getText());

        OrderClass order = new OrderClass(name_c, product_order, quantity_products_order);

        for (StocktakingClass stocktaking : stocktaking_list) {
            if (stocktaking.getName_product().equals(product_order)) {
                if (quantity_products_order <= stocktaking.getQuantity_product()) {

                    order_list.add(order);
                    clean_fields_order();

                    int new_quantity_product = stocktaking.getQuantity_product() - quantity_products_order;
                    stocktaking.setQuantity_product(new_quantity_product);
                    this.add_stock_list();

                    int price_product = stocktaking.getPrice_product();
                    int value_pay = quantity_products_order * stocktaking.getPrice_product();

                    SimpleorderClass order_pay = new SimpleorderClass(name_c, product_order, quantity_products_order, price_product, value_pay);
                    simple_list.add(order_pay);
                    add_order_pay();

                } else {
                    JOptionPane.showMessageDialog(this, "No hay suficientes productos para cubrir su orden");
                }
            }
        }
    }//GEN-LAST:event_btn_add_orderActionPerformed

    private void btn_amount_card_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_amount_card_payActionPerformed
        String number_card = txt_card_number.getText();

        for (CardClass card_information : card_list) {
            if (number_card.equals(card_information.getNumber_card())) {
                String message = " El saldo del la tarjeta número " + card_information.getNumber_card() + " es $" + card_information.getAmount_card();
                txtarea_amount_card.setText(message);
                break;
            } else {
                JOptionPane.showMessageDialog(this, "El numero de la tarjeta no se encuentra agregada en el sistema");
                break;
            }
        }
    }//GEN-LAST:event_btn_amount_card_payActionPerformed

    private void btn_recharge_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recharge_cardActionPerformed
        int value_recharge_card = Integer.parseInt(txt_recharge_card.getText());
        String card_number = txt_card_number.getText();

        for (CardClass card_information : card_list) {
            if (card_number.equals(card_information.getNumber_card())) {

                int new_value_card = card_information.getAmount_card() + value_recharge_card;
                card_information.setAmount_card(new_value_card);

                String message = " El saldo del la tarjeta número " + card_information.getNumber_card() + " es $" + card_information.getAmount_card();
                txtarea_amount_card.setText(message);

            }
        }
    }//GEN-LAST:event_btn_recharge_cardActionPerformed

    private void btn_order_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order_payActionPerformed

        int total_value_pay = 0;
        int quantity_products = 0;
        String name_client = txt_name_c_pay.getText();
        String number_card = txt_card_pay.getText();

        for (SimpleorderClass order_pay : simple_list) {
            if (name_client.equals(order_pay.getClient_name())) {
//              
                total_value_pay = total_value_pay + order_pay.getTotal_value();

                String client_name = order_pay.getClient_name();
                String product_order = order_pay.getProduct_ordered();
                int quantity = order_pay.getQuantity_ordered();
                int price = order_pay.getPrice();
                int total_value = order_pay.getTotal_value();

                CompoundClass compound_order = new CompoundClass(client_name, product_order, quantity, price, total_value);
                compound_list.add(compound_order);

                add_order_pay_list();

                quantity_products = quantity_products + quantity;
            }
        }

        OrderStage stage = new OrderStage(name_client, number_card, total_value_pay);
        orderstage_list.add(stage);

        String mesagge_pay = " El valor total a pagar es:  $ " + total_value_pay;
        txt_area_total_pay.setText(mesagge_pay);

        if (quantity_products <= 20) {
            JOptionPane.showMessageDialog(this, "Orden simple: su orden contiene menos de 20 unidades. Por favor continue con el pago");
        } else {
            JOptionPane.showMessageDialog(this, "Orden compuesta: su orden contiene mas de 20 unidades. Por favor continue con el pago");
        }
    }//GEN-LAST:event_btn_order_payActionPerformed

    private void btn_pay_nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pay_nowActionPerformed

        String name_client = txt_name_c_pay.getText();
        String card_number = txt_card_pay.getText();
        int total_value = 0;

        for (OrderStage stage : orderstage_list) {
            if (stage.getClient_name().equals(name_client)) {
                int value_pay = stage.getTotal_value();
                total_value = value_pay;
            }
        }

        for (CardClass card_information : card_list) {
            while (card_information.getName_client().equals(name_client)) {

                if (total_value <= card_information.getAmount_card()) {

                    int pay = card_information.getAmount_card() - total_value;
                    card_information.setAmount_card(pay);

                    JOptionPane.showMessageDialog(this, "La orden se ha pagado con exito");
                    clean_fields_pay();

                    for (CompoundClass compound : compound_list) {
                        compound_list.remove();
                    }

                    OrderStage distribution = new OrderStage(name_client, card_number, total_value);
                    distribution_list.add(distribution);
                    add_distribution_list();

                    break;

                } else {
                    JOptionPane.showMessageDialog(this, "Valor insuficiente, intente con otra cuenta");
                    clean_fields_pay();
                    for (CompoundClass compound : compound_list) {
                        compound_list.remove();
                    }
                    break;
                }

            }
        }


    }//GEN-LAST:event_btn_pay_nowActionPerformed

    private void btn_pay_afterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pay_afterActionPerformed
        JOptionPane.showMessageDialog(this, "El saldo correspondiente a su orden sera recordado una vez al dia");
        String name_client = txt_name_c_pay.getText();

        for (OrderStage stage : orderstage_list) {
            if (name_client.equals(stage.getClient_name())) {

                String name = stage.getClient_name();
                String card = stage.getCard_number();
                int value = stage.getTotal_value();

                OrderStage charge_order = new OrderStage(name, card, value);
                charge_list.add(charge_order);
            }
        }
        add_order_stage_list();

    }//GEN-LAST:event_btn_pay_afterActionPerformed

    private void btn_add_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_cardActionPerformed
        String name_c_pay = txt_name_c_pay.getText();
        String card_pay = txt_card_pay.getText();
        int amount_card = 0;

        CardClass card_information = new CardClass(name_c_pay, card_pay, amount_card);
        card_list.add(card_information);

        JOptionPane.showMessageDialog(this, "Tarjeta agregada con exito");

    }//GEN-LAST:event_btn_add_cardActionPerformed

    private void btn_order_stageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order_stageActionPerformed
        String order_name = txt_name_client_stage1.getText();

        for (OrderStage stage : charge_list) {
            if (order_name.equals(stage.getClient_name())) {

                String client_name = stage.getClient_name();
                String card_number = stage.getCard_number();
                int total_value = 0;

                OrderStage distribution = new OrderStage(client_name, card_number, total_value);
                distribution_list.add(distribution);
                charge_list.remove(distribution);

                add_order_stage_list();
                add_distribution_list();

            }
        }

    }//GEN-LAST:event_btn_order_stageActionPerformed

    private void btn_distribution_stageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distribution_stageActionPerformed
        String order_name = txt_name_client_stage2.getText();

        for (OrderStage distribution : distribution_list) {
            if (order_name.equals(distribution.getClient_name())) {

                String client_name = distribution.getClient_name();
                String card_number = distribution.getCard_number();
                int total_value = 0;

                OrderStage confirmation = new OrderStage(client_name, card_number, total_value);
                confirmation_list.add(confirmation);
                distribution_list.remove(confirmation);

                add_distribution_list();
                add_confirmation_list();

            }
        }
    }//GEN-LAST:event_btn_distribution_stageActionPerformed

    //********************* AÑADIR A LISTAS***************************** 
    public void add_stock_list() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (StocktakingClass stocktaking : stocktaking_list) {
            String stock = stocktaking.getName_product() + " - " + stocktaking.getPrice_product() + " - " + stocktaking.getQuantity_product();
            model.add(index_model, stock);
            index_model++;
        }
        stock_list.setModel(model);
    }

    public void add_order_pay() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (SimpleorderClass order_pay : simple_list) {
            String order = "Nombre del cliente: " + order_pay.getClient_name() + "    Referencia del producto: " + order_pay.getProduct_ordered() + "    Cantidad: " + order_pay.getQuantity_ordered() + "    Precio unidad: " + order_pay.getPrice() + "    Valor total: " + order_pay.getTotal_value();
            model.add(index_model, order);
            index_model++;
        }
        order_client_list.setModel(model);
    }

    public void add_order_pay_list() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (CompoundClass compound_order : compound_list) {
            String order = "Nombre del cliente: " + compound_order.getClient_name() + "    Referencia del producto: " + compound_order.getProduct_ordered() + "    Cantidad: " + compound_order.getQuantity_ordered() + "    Precio unidad: " + compound_order.getPrice() + "    Valor total: " + compound_order.getTotal_value();
            model.add(index_model, order);
            index_model++;
        }
        order_pay_list.setModel(model);
    }

    public void add_order_stage_list() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (OrderStage stage : charge_list) {
            String charge_stage = "Nombre del cliente: " + stage.getClient_name() + "    Tarjeta de credito No." + stage.getCard_number() + "    Valor a pagar: " + stage.getTotal_value();
            model.add(index_model, charge_stage);
            index_model++;
        }
        order_stage_list.setModel(model);
    }

    public void add_distribution_list() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (OrderStage distribution : distribution_list) {
            String distribution_stage = "Nombre del cliente: " + distribution.getClient_name() + "    Tarjeta de credito No." + distribution.getCard_number() + "    Valor a pagar: " + distribution.getTotal_value();
            model.add(index_model, distribution_stage);
            index_model++;
        }
        distribution_stage_list.setModel(model);
    }
    
    public void add_confirmation_list() {
        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (OrderStage confirmation : confirmation_list) {
            String confirmation_stage = "Nombre del cliente: " + confirmation.getClient_name() + "    Tarjeta de credito No." + confirmation.getCard_number() + "    Valor a pagar: " + confirmation.getTotal_value();
            model.add(index_model, confirmation_stage);
            index_model++;
        }
        confirmation_stage_list.setModel(model);
    }

    //************************LIMPIAR CAMPOS***************************************************
    public void clean_fields() {
        txt_name_product_stocktaking.setText("");
        txt_price_stocktaking.setText("");
        txt_quantity_stocktaking.setText("");
    }

    public void clean_fields_order() {
        txt_name_client_order.setText("");
        txt_address_client.setText("");
        txt_phone_client.setText("");
        txt_email_client.setText("");
        txt_product_order.setText("");
        txt_quantity_order.setText("");
    }

    public void clean_fields_pay() {
        txt_name_c_pay.setText("");
        txt_card_pay.setText("");
        txt_area_total_pay.setText("");
        txtarea_amount_card.setText("");
        txt_recharge_card.setText("");
        order_pay_list.removeAll();
        txt_card_number.setText("");

        DefaultListModel model = new DefaultListModel();
        int index_model = 0;
        for (CompoundClass compound_order : compound_list) {
            String order = " ";
            model.add(index_model, order);
            index_model++;
        }
        order_pay_list.setModel(model);

    }
    //********************************************************************************************

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_card;
    private javax.swing.JButton btn_add_order;
    private javax.swing.JButton btn_add_stock;
    private javax.swing.JButton btn_amount_card_pay;
    private javax.swing.JButton btn_distribution_stage;
    private javax.swing.JButton btn_order_pay;
    private javax.swing.JButton btn_order_stage;
    private javax.swing.JButton btn_pay_after;
    private javax.swing.JButton btn_pay_now;
    private javax.swing.JButton btn_recharge_card;
    private javax.swing.JList<String> confirmation_stage_list;
    private javax.swing.JList<String> distribution_stage_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JList<String> order_client_list;
    private javax.swing.JList<String> order_pay_list;
    private javax.swing.JList<String> order_stage_list;
    private javax.swing.JList<String> stock_list;
    private javax.swing.JTextField txt_address_client;
    private javax.swing.JTextArea txt_area_total_pay;
    private javax.swing.JTextField txt_card_number;
    private javax.swing.JTextField txt_card_pay;
    private javax.swing.JTextField txt_email_client;
    private javax.swing.JTextField txt_name_c_pay;
    private javax.swing.JTextField txt_name_client_order;
    private javax.swing.JTextField txt_name_client_stage1;
    private javax.swing.JTextField txt_name_client_stage2;
    private javax.swing.JTextField txt_name_product_stocktaking;
    private javax.swing.JTextField txt_phone_client;
    private javax.swing.JTextField txt_price_stocktaking;
    private javax.swing.JTextField txt_product_order;
    private javax.swing.JTextField txt_quantity_order;
    private javax.swing.JTextField txt_quantity_stocktaking;
    private javax.swing.JTextField txt_recharge_card;
    private javax.swing.JTextArea txtarea_amount_card;
    // End of variables declaration//GEN-END:variables
}
